### ISSUE TITLE
[Meta] Slack team for slack-statistics?

### ISSUE THREAD

**Issue by pvdsp** [pvdsp/slack-statistics#11]
Would someone be interested in a Slack channel for this project? It's amazing to work with you all and I want to keep in touch to make slack-statistics something great! Let me know what you think and if there's enough response, I'll make one first thing tomorrow.

**Comment by Marlysson** [comment]
Whats you think about use the telegram APP? More easy and very cool :D

**Comment by pvdsp** [comment]
We can always use the telegram app if you want

**Comment by Marlysson** [comment]
Some group already created?

**Comment by yasinS** [comment]
I use Slack for collaboration (might be useful for bug-fix discussion etc) but not Telegram unfortunately.
