### ISSUE TITLE
Fix line-height in CSS

### ISSUE THREAD

**Issue by pvdsp** [pvdsp/slack-statistics#12]
When the most talkative user of the day has a long name, the name will be wrongly displayed. Is there a possibility for a fix?

**Comment by yasinS** [comment]
@pvdsp Able to word-wrap the data fields to prevent overflow, although this still causes readability issues. Should be able to come up with a better solution (responsive resize) shortly!

<img width="375" alt="word wrap" src="https://cloud.githubusercontent.com/assets/4115778/19679380/7276071c-9a99-11e6-8d2c-1f556962da0e.png">

**Comment by pvdsp** [comment]
@yasinS: that jQuery plugin seems like a great idea!

**Comment by yasinS** [comment]
@pvdsp The docs are nice and straightforward but I'm having trouble using it. Just seeing if there are any similar snippets out there!

**Comment by pvdsp** [comment]
@yasinS If you're ready, you can push the changes yourself now that you're a collaborator.

**Comment by yasinS** [comment]
Think this issue can be closed now. Thanks again @JacobJangles!
