### ISSUE TITLE
Ideas for new features?

### ISSUE THREAD

**Issue by pvdsp** [pvdsp/slack-statistics#14]
If you have an idea for a new feature for Slack Statistics, please post here.

**Comment by yasinS** [comment]
We could display the talkative user's profile picture alongside (or instead of) their name? If it's for internal use, might be a workaround to the font size issues.

**Comment by yasinS** [comment]
Also, should we [choose an open-source license](http://choosealicense.com/) and [import](https://help.github.com/articles/adding-a-license-to-a-repository/) this into the repo?

**Comment by pvdsp** [comment]
@yasinS I was thinking about an MIT or GNU GPLv3 license. What is your opinion on this?

**Comment by yasinS** [comment]
@pvdsp Given the permissive and open nature of the project, I'm thinking MIT. Succinct and straightforward to implement, used by jQuery etc. Seems like it's the most [common](https://github.com/blog/1964-open-source-license-usage-on-github-com) on GitHub too.

**Comment by pvdsp** [comment]
@yasinS Let's pick MIT

**Comment by yasinS** [comment]
@pvdsp License added to master branch!

**Comment by pvdsp** [comment]
I'll close this issue for now, we can think about new ideas after we get all the bugs out of the current version.
