### ISSUE TITLE
UserMessageCount is not correct

### ISSUE THREAD

**Issue by pvdsp** [pvdsp/slack-statistics#22]
I've noticed that since a pull request of today, `UserMessageCount` (and, obviously, `UserMostTalkative`) is not correct. I'm trying to find a solution.

**Comment by yasinS** [comment]
@pvdsp Investigating, think I've got the same issue in my test Slack.

**Comment by pvdsp** [comment]
@david1983 Any idea what could've gone wrong? I think the code broke since implementing it with `fetch`.

**Comment by david1983** [comment]
@pvdsp Can you make an example ?
I've tried to checkout the commit before the pull request and it shows the same data of the latest version
`git checkout b60e5066a998457e61741efc93995e351abbcbe3`

This is the screen of the b60e5066a998457e61741efc93995e351abbcbe3
![screenshot_2016-10-26_08-27-07](https://cloud.githubusercontent.com/assets/6210160/19716990/77f0fe8c-9b56-11e6-9cf2-e44feef7883a.png)

This is the screen of the latest version
![screenshot_2016-10-26_08-28-00](https://cloud.githubusercontent.com/assets/6210160/19717007/89c6f5f8-9b56-11e6-8d26-3e48aeb69359.png)

**Comment by pvdsp** [comment]
I'll let you know when I can replicate it. The issue was that the number of messages for each user didn't add up. The most talkative user of my slack team had well over a hundred messages, but Slack Statistics chose another user as most talkative, and printed that he had 20 messages (he, also, had over a hundred messages)

**Comment by pvdsp** [comment]
@david1983 

![screenshot 1](https://puu.sh/rW9LB/79514ed17e.png)
![screenshot 2](https://puu.sh/rW9LA/952633d1ef.png)

**Comment by yasinS** [comment]
As noted [here](https://github.com/pvdsp/slack-statistics/issues/24#issuecomment-256258885), I'm unable to compile the Bower add-in components on my local build to test this. I'm not very experienced with Bower so probably missing a key step! Please can you assist @david1983?

**Comment by yasinS** [comment]
@pvdsp Bower issues resolved and `userMessageCount` now appears to be correct! Latest updates close issue #24.

**Comment by pvdsp** [comment]
We unfortunately still have the issue that `userMessageCount` is incorrect. Slack Statistics displays 20 messages for the most talkative user, but in reality he has 132.

**Comment by pvdsp** [comment]
As far as I'm concerned, this bug is fixed. I will close the issue. Be free to re-open if the bug isn't completely fixed.

**Comment by yasinS** [comment]
Great to hear @pvdsp @david1983 – thanks for the update!
