### ISSUE TITLE
[Safari-only] Unable to establish Slack connection – fetch error

### ISSUE THREAD

**Issue by yasinS** [pvdsp/slack-statistics#24]
Just tested latest build on Safari with my test Slack token – appears data isn't being fetched correctly. Seems to be the same issue as referenced [here](https://stackoverflow.com/questions/35830202/fetch-not-defined-in-safari-referenceerror-cant-find-variable-fetch).

### Scope
Safari-only, works fine in other browser environments. 

### Error
`Can't find variable: fetch` on Line 82 

### Involved function

```
function TeamInfoRequest(){
    return fetch("https://slack.com/api/team.info?token=" + slackToken, requestOptions).then((response)=>{return response.json()});
}
```

**Comment by pvdsp** [comment]
@yasinS Can you test if this bug is still appearing?

**Comment by yasinS** [comment]
@pvdsp Just trying to test now but unsure on how to initialise Bower and compile. Doesn't seem like `bower.json` contains any packages? Will be able to add these steps to `README.md` when working.

**Comment by pvdsp** [comment]
@yasinS I, unfortunately, am not familiar with Bower. I'm afraid I can't help for now. I'm trying to find it out.

**Comment by pvdsp** [comment]
@yasinS Is it fixed now? I can't test atm but I changed the paths to a cdn.

**Comment by yasinS** [comment]
Closing issue, resolved as noted [here](https://github.com/pvdsp/slack-statistics/issues/22#issuecomment-256348904).
