### ISSUE TITLE
Improve CSS / create new layout

### ISSUE THREAD

**Issue by pvdsp** [pvdsp/slack-statistics#3]
Everyone is welcome to edit the CSS to improve the layout of Slack Statistics.

**Comment by Marlysson** [comment]
Which of these is the better , the style is the number stay above and description of statistics below of number.

https://br.pinterest.com/pin/463518986628706760/
https://br.pinterest.com/pin/397513104591613391/

**Comment by yasinS** [comment]
@pvdsp Started working on some updates to docs and CSS – have forked to experiment with layouts.

**Comment by pvdsp** [comment]
@Marlysson: Great idea to put the description under the numbers! The second link of pinterest seems great!
@yasinS: Great to hear, good luck!

**Comment by pvdsp** [comment]
@yasinS Amazing work! I'll let this issue open for now, but I'll put you as assignee.

**Comment by yasinS** [comment]
@pvdsp Thank you very much!

**Comment by Marlysson** [comment]
Still open to layouts's options? :D

**Comment by pvdsp** [comment]
@Marlysson you're welcome to share; we can always take the good elements out and use them in the current layout.

**Comment by pvdsp** [comment]
I'll close this issue for now, design is good as it is at the moment.
