### ISSUE TITLE
Elements not centered after adding fullPage.js

### ISSUE THREAD

**Issue by pvdsp** [pvdsp/slack-statistics#31]
Some elements of the page (the coloured rectangles with our data) are not centered anymore after adding the leaderboards + fullPage.js. 

**Expected:** horizontally center the three rectangles on the page.

**Comment by mohtamohit** [comment]
Hi, I would like to work on this issue.

**Comment by pvdsp** [comment]
Great! You're welcome to send a pull request!

**Comment by mohtamohit** [comment]
HackOctoberfest tag removed?

**Comment by pvdsp** [comment]
@mohtamohit I removed the tags and replaced is with "in progress" because you're working on it. Sorry for the confusion. It was just so that other people know that you're claiming this issue.

**Comment by mohtamohit** [comment]
Please do add the "hackoctoberfest" tag back so that I can get show the work for gaining points. Review the PR : https://github.com/pvdsp/slack-statistics/pull/34 . The issue has been resolved. Thanks! :)

**Comment by pvdsp** [comment]
Hi, @mohtamohit, the "hacktoberfest" label is not required for getting the free T-shirt. You can work on any repository you like, have fun!

**Comment by pvdsp** [comment]
You can always enter your username [here](http://hacktoberfestchecker.herokuapp.com/) to see how many PRs you have left to send

**Comment by pvdsp** [comment]
Thanks for the fix, @mohtamohit! I'll close this issue now.
