### ISSUE TITLE
Edit CSS for leaderboards

### ISSUE THREAD

**Issue by pvdsp** [pvdsp/slack-statistics#32]
I added a new functionality (leaderboards), but did not make a CSS. Does someone want to make a nice layout for the leaderboards (in the style of the first page)?

**Comment by yasinS** [comment]
@pvdsp Great feature idea! Should be able to work on something over the next day or two.

**Comment by pvdsp** [comment]
@yasinS Thanks, and great!

**Comment by yasinS** [comment]
Still unsure what's causing the JS issues noted in issue #35. Regardless, started working on leaderboard design in 2ddd12d39b5ab05e544f6575fd2b4a57142ea1f0.

**Comment by yasinS** [comment]
Closing this issue as we've now got a functional CSS design for the leaderboard.
