### ISSUE TITLE
XSS and arbitrary code execution – risk to consider?

### ISSUE THREAD

**Issue by yasinS** [pvdsp/slack-statistics#33]
A Slack user can inject **arbitrary HTML code** into their First Name, which is executed through the "Most Talkative User" and Leaderboard when the board is loaded. 

This can include **malicious XSS payloads**; please refer to [this](https://www.owasp.org/index.php/Testing_for_Stored_Cross_site_scripting_(OTG-INPVAL-002)) guide for an explanation of risks. Given that this is an internal tool, the impact is limited but present.

The web server admin can add the `X-XSS-Protection` [header](https://www.owasp.org/index.php/OWASP_Secure_Headers_Project#X-XSS-Protection). This should stop XSS payloads running on their page (but not HTML code).

Should we look at implementing some kind of built-in [protection](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet)?

### Example payloads
`<h1 style="color:yellow;">Hi</h1>`
`<audio src=1 onerror=alert(1)>`
`<video src=1 onerror=alert(1)>`

<img width="360" alt="HTML injection" src="https://cloud.githubusercontent.com/assets/4115778/19816914/2ac8d6f6-9d41-11e6-8e04-1c983a74813b.png">

<img width="1127" alt="Cross Site Scripting" src="https://cloud.githubusercontent.com/assets/4115778/19816923/3120f68c-9d41-11e6-9e96-f44341c4559b.png">

**Comment by pvdsp** [comment]
XSS (Cross Site Scripting) Prevention seems like a must on the long-term, but isn't really a priority at this moment (imo). But everyone who has the know-how on this prevention is more than welcome to implement these techniques!

**Comment by yasinS** [comment]
Should be able to implement a basic encoder to mitigate these payloads – in progress!
