### ISSUE TITLE
Prompt user for their token

### ISSUE THREAD

**Issue by itsdegan** [pvdsp/slack-statistics#35]
Going forward should there be a prompt to get the users token and then the appropriate calls are made or is something else being considered?

**Comment by pvdsp** [comment]
@itsdegan What do you think about [this](https://api.slack.com/docs/sign-in-with-slack)?

**Comment by yasinS** [comment]
@pvdsp Token is accepted via the prompt with no issues; this error appears after data is fetched though: `TypeError: Cannot read property 'member' of undefined. Ensure you have added your API token into stats.js`

**Comment by pvdsp** [comment]
@yasinS Weird, I can't seem to replicate this issue. I'll investigate further.

**Comment by yasinS** [comment]
It's very unusual, as the Statistics board still loads the correct data. Also getting a different JS error in Safari: 
```
TypeError: undefined is not an object (evaluating 'userTalkativeRanking[2].member'). 
Ensure you have added your API token into stats.js
```

**Comment by pvdsp** [comment]
@yasinS How many members do you have in your Slack server? I think this issue is caused by the fact that the leaderboards want to pull data for third place, but isn't able to.

**Comment by yasinS** [comment]
@pvdsp Was just about to reply regarding that :) Just tested with a prod Slack team and it's working fine. Please disregard this issue, it's just my test environment!

**Comment by pvdsp** [comment]
@yasinS Great to hear!
