### ISSUE TITLE
Documenting JavaScript Code

### ISSUE THREAD

**Issue by pvdsp** [pvdsp/slack-statistics#6]
To make slack-statistics accessible for newcomers, it would be nice if someone could take the time to document the code such that someone with a basic understanding of JavaScript could easily understand it.
*Example: comments on what is happening with the promises, the API calls, etc.*

**Comment by itsdegan** [comment]
Provided this isn't super time critical I could take a look at it.

**Comment by david1983** [comment]
I would refactor the data function in smaller bits, 
so you can chain like 
.then(fnName1).then(fnName2)....
and maybe you can use fetch() instead of xmlHttpRequest that provides already a Promise based implementation.

**Comment by itsdegan** [comment]
@pvdsp At least for the existing code is this the level of detail you are looking for?  I would like to make this more concise without sacrificing clarity but do you think something like this is too specific?

```javascript
function getData() {
    /* Chain all the requests and console.log caught errors.
	   After each successful call the next call will execute, however if a 
	   call fails there will be no more calls and the error will be logged */
    data(null, "info", "teamName")
        .then(() => data(todayQuery, "search", "todayCount"))
        .then(() => data(yesterdayQuery, "search", "yesterdayCount"))
        .then(() => data(null, "users", "userCount"))
        .then(() => data(null, "users", "userList"))
        .then(() => getPercentage())
        .then(() => getTalkativeUser())
        .then(() => postToHTML())
        .catch(error => console.log(error))
};
```

**Comment by pvdsp** [comment]
@itsdegan: that's exactly what I meant, you're welcome to document in when you have the time.
@david1983: great idea! You're welcome to send a pull request at any time, if it works and it's cleaner than the current version, we'll aprove it

**Comment by itsdegan** [comment]
I'll make adjustments to the inline documentation based off the recent commits and have a PR ready soon.

**Comment by itsdegan** [comment]
Made PR #30 to address this

**Comment by pvdsp** [comment]
Amazing work, I'll close this issue. Thanks!
